-- Migration for Temporary GC Feature
-- This creates tables for temporary GC management with locking mechanism

-- Table for storing temporary GC templates created by admin
DROP TABLE IF EXISTS `temporary_gc`;

CREATE TABLE `temporary_gc` (
  `id` int NOT NULL AUTO_INCREMENT,
  `temp_gc_number` varchar(50) NOT NULL UNIQUE,
  `created_by_user_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_locked` tinyint(1) DEFAULT 0,
  `locked_by_user_id` int DEFAULT NULL,
  `locked_at` timestamp NULL DEFAULT NULL,
  `is_converted` tinyint(1) DEFAULT 0,
  `converted_gc_number` varchar(300) DEFAULT NULL,
  `converted_by_user_id` int DEFAULT NULL,
  `converted_at` timestamp NULL DEFAULT NULL,
  
  -- GC Form Fields (partially filled by admin)
  `BranchCode` varchar(300) DEFAULT NULL,
  `Branch` varchar(300) DEFAULT NULL,
  `GcDate` varchar(300) DEFAULT NULL,
  `TruckNumber` varchar(300) DEFAULT NULL,
  `vechileNumber` varchar(300) DEFAULT NULL,
  `TruckType` varchar(300) DEFAULT NULL,
  `BrokerNameShow` varchar(300) DEFAULT NULL,
  `BrokerName` varchar(300) DEFAULT NULL,
  `TripId` varchar(300) DEFAULT NULL,
  `PoNumber` varchar(300) DEFAULT NULL,
  `TruckFrom` varchar(300) DEFAULT NULL,
  `TruckTo` varchar(300) DEFAULT NULL,
  `PaymentDetails` varchar(300) DEFAULT NULL,
  `LcNo` varchar(300) DEFAULT NULL,
  `DeliveryDate` varchar(300) DEFAULT NULL,
  `EBillDate` varchar(300) DEFAULT NULL,
  `EBillExpDate` varchar(300) DEFAULT NULL,
  `DriverNameShow` varchar(300) DEFAULT NULL,
  `DriverName` varchar(300) DEFAULT NULL,
  `DriverPhoneNumber` varchar(300) DEFAULT NULL,
  `Consignor` varchar(900) DEFAULT NULL,
  `ConsignorName` varchar(900) DEFAULT NULL,
  `ConsignorAddress` varchar(900) DEFAULT NULL,
  `ConsignorGst` varchar(900) DEFAULT NULL,
  `Consignee` varchar(900) DEFAULT NULL,
  `ConsigneeName` varchar(900) DEFAULT NULL,
  `ConsigneeAddress` varchar(900) DEFAULT NULL,
  `ConsigneeGst` varchar(900) DEFAULT NULL,
  `CustInvNo` varchar(300) DEFAULT NULL,
  `InvValue` varchar(300) DEFAULT NULL,
  `EInv` varchar(300) DEFAULT NULL,
  `EInvDate` varchar(300) DEFAULT NULL,
  `Eda` varchar(300) DEFAULT NULL,
  `NumberofPkg` varchar(300) DEFAULT NULL,
  `MethodofPkg` varchar(300) DEFAULT NULL,
  `TotalRate` varchar(1000) DEFAULT NULL,
  `TotalWeight` varchar(300) DEFAULT NULL,
  `Rate` varchar(300) DEFAULT NULL,
  `km` varchar(250) DEFAULT NULL,
  `km2` varchar(250) DEFAULT NULL,
  `km3` varchar(250) DEFAULT NULL,
  `km4` varchar(250) DEFAULT NULL,
  `ActualWeightKgs` varchar(300) DEFAULT NULL,
  `Total` varchar(300) DEFAULT NULL,
  `PrivateMark` varchar(300) DEFAULT NULL,
  `PrivateMark2` varchar(300) DEFAULT NULL,
  `PrivateMark3` varchar(300) DEFAULT NULL,
  `PrivateMark4` varchar(300) DEFAULT NULL,
  `Charges` varchar(300) DEFAULT NULL,
  `Charges2` varchar(300) DEFAULT NULL,
  `Charges3` varchar(300) DEFAULT NULL,
  `Charges4` varchar(300) DEFAULT NULL,
  `NumberofPkg2` varchar(300) DEFAULT NULL,
  `MethodofPkg2` varchar(300) DEFAULT NULL,
  `Rate2` varchar(300) DEFAULT NULL,
  `Total2` varchar(300) DEFAULT NULL,
  `ActualWeightKgs2` varchar(300) DEFAULT NULL,
  `NumberofPkg3` varchar(300) DEFAULT NULL,
  `MethodofPkg3` varchar(300) DEFAULT NULL,
  `Rate3` varchar(300) DEFAULT NULL,
  `Total3` varchar(300) DEFAULT NULL,
  `ActualWeightKgs3` varchar(300) DEFAULT NULL,
  `NumberofPkg4` varchar(300) DEFAULT NULL,
  `MethodofPkg4` varchar(300) DEFAULT NULL,
  `Rate4` varchar(300) DEFAULT NULL,
  `Total4` varchar(300) DEFAULT NULL,
  `ActualWeightKgs4` varchar(300) DEFAULT NULL,
  `GoodContain` varchar(900) DEFAULT NULL,
  `GoodContain2` varchar(900) DEFAULT NULL,
  `GoodContain3` varchar(300) DEFAULT NULL,
  `GoodContain4` varchar(300) DEFAULT NULL,
  `DeliveryFromSpecial` varchar(900) DEFAULT NULL,
  `DeliveryAddress` varchar(900) DEFAULT NULL,
  `ServiceTax` varchar(300) DEFAULT NULL,
  `ReceiptBillNo` varchar(300) DEFAULT NULL,
  `ReceiptBillNoAmount` varchar(300) DEFAULT NULL,
  `ReceiptBillNoDate` varchar(300) DEFAULT NULL,
  `ChallanBillNoDate` varchar(255) DEFAULT NULL,
  `ChallanBillAmount` varchar(255) DEFAULT NULL,
  `HireAmount` varchar(300) DEFAULT NULL,
  `AdvanceAmount` varchar(300) DEFAULT NULL,
  `BalanceAmount` varchar(300) DEFAULT NULL,
  `FreightCharge` varchar(300) DEFAULT NULL,
  `CompanyId` varchar(900) DEFAULT NULL,
  
  PRIMARY KEY (`id`),
  KEY `idx_temp_gc_number` (`temp_gc_number`),
  KEY `idx_is_converted` (`is_converted`),
  KEY `idx_is_locked` (`is_locked`),
  KEY `idx_company_id` (`CompanyId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Add created_at column to gc_creation table if not exists
-- This helps track when GC was created for 24-hour edit restriction
ALTER TABLE `gc_creation` 
ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `CompanyId`,
ADD COLUMN IF NOT EXISTS `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_at`,
ADD COLUMN IF NOT EXISTS `created_by_user_id` int DEFAULT NULL AFTER `updated_at`;

-- Index for faster queries
CREATE INDEX IF NOT EXISTS `idx_gc_created_at` ON `gc_creation` (`created_at`);
CREATE INDEX IF NOT EXISTS `idx_gc_company_created` ON `gc_creation` (`CompanyId`, `created_at`);
